contactform:
  description: This is a demo contact form and does not work. You can configure it
    to work on your side.
  emailconfig: abc
facts:
  experience: 5
  projects: 25
  customers: 100
keywords: "portfolio, website, netlify, jekyll, resume, mihir mer, "
author:
  resumelink: https://google.com
  name: Mihir Mer
  cvlink: https://google.com
  phone: +91 940 889 6806
  first: Mihir
  address: Gujarat, IN
  last: Mer
  dob: 19 Nov 2000
  passion: App Developer, Web Developer, Graphic Designer, Programmer
  languages: English, Gujarati, Hindi
  image: /assets/uploads/mihir-mer.png
  nationality: INDIAN
  email: mihirmer2000@gmail.com
  description: I am a Developer and Designer from India. I am very passionate and
    dedicated to my work. I enjoy working in a team or individual. Have worked
    on various Web Application and Mobile Application Projects. Excited to learn
    new Technologies.
social:
  facebook: mr.kaushal.p
  github: mrkp
  instagram: mr.kaushal.p
  linkedin: mrkaushalp
url: ""
collections:
  portfolio:
    output: true
title: Mihir Mer
description: My Portfolio
baseurl: ""
